== Resources

We almost have all the building blocks in place now.
Let's see how to set everything up so that we can finally get started with our first project.

=== AIR SDK

If you have picked and installed your IDE, the next step is to download the latest version of the _AIR SDK_.
Each new release typically contains several important bug-fixes, which is especially important to maintain compatibility with the latest mobile operating systems.
Thus, it's recommended to always use the very latest version, and to keep an eye on the latest release notes.

Beginning with version 33, AIR is being developed and supported by _Harman_.
You can find it here: https://airsdk.harman.com/download[Download AIR SDK from Harman].

[NOTE]
====
If you don't want to use Harman's AIR release for some reason (e.g. licensing issues), it's still possible to use _AIR 32_ from Adobe – at least when targeting the Desktop.
That is, if you have a copy lying around, because Adobe doesn't provide it any longer.
Also note that this version received its final security update in late 2020.
====

.Fixing an Issue on macOS
****
If you're developing on _macOS Catalina_ or later, you might be confronted with an error like the following when you compile your project:

* "[A binary] cannot be opened because the Developer cannot be verified."
* "macOS cannot verify that this app is free from malware."
* "Adobe AIR.framework can't be opened because Apple cannot check it for malicious software."

The latest macOS versions require all executables to be "notarized" by Apple; however, the AIR SDK still contains some executables that don't satisfy that requirement.
Hopefully, this is soon fixed by _Harman_; in the meantime, there is an easy workaround.

Open up the _Terminal_ and navigate to the parent folder of your AIR SDK.
Then execute the following command:

    sudo xattr -r -d com.apple.quarantine [air_sdk_folder]

Now enter your admin passwort when you're prompted, and the compilation issues should be gone.
****

=== Flash Player Projector

After the "death" of _Flash Player_, you technically don't need the _Flash Player Projector_ any longer.
That's a standalone version of the plugin that doesn't require a browser to run Flash content.

However, it's still a great way to play around with ActionScript and Starling without the hassle of setting up a complete AIR project.
Furthermore, you can use the projector to view legacy Flash content ("SWF movies", as they called them), so I recommend you grab a copy before Adobe removes it altogether!

Downloads for all operating systems are available here (look for the "projector content debugger"):
https://www.adobe.com/support/flashplayer/debug_downloads.html[Adobe Flash Player Debug Downloads]

NOTE: The debugger is significantly slower than the standard version.
Keep that in mind when you are working on performance optimization.

Your IDE might need to know how to find the correct player.
For example, in _IDEA_, this setting is part of the debug configurations screen; other IDEs might simply use the system default.
In any case, it's important to always use a player version that's equal to or higher than the AIR SDK version you compiled the SWF with.

=== Starling

Now all that's left to download is Starling itself.
You can choose between two ways of doing that.

a. Download the latest release as a zip-file from the http://gamua.com/starling/download/[Gamua website].
b. Clone Starling's _Git_ repository.

The advantage of the former is that it comes with a precompiled SWC file (found in the folder `starling/bin`) that is easily linked to your project.
However, you'll always only get the stable releases this way, which means you're missing out on the latest hot updates and fixes!
For this reason, I'd rather advocate using _Git_.

TIP: Let's say you report a bug and it is fixed a few days later (yes, that happens!): with the standard download, you'll have to wait for the fix until I'm creating a new stable release, which could be quite a while.
When you're using the _Git_ repository, you'll have the fix right away.

Going into depths about _Git_ would exceed the scope of this manual, but you'll find lots of great tutorials about it on the web.
Once installed, _Git_ can _clone_ the complete Starling repository to your disk with the following command:

  git clone https://github.com/Gamua/Starling-Framework.git

This will copy Starling to the folder `Starling-Framework`.
Look for the actual source code inside the sub-folder `starling/src`.
All of the mentioned IDEs support adding this folder as a _source path_ to your project, which will make Starling part of your project.
That's not any more complicated than linking to the SWC file; and as a neat side effect, you will even be able to step into Starling's source on debugging.

But what's best about this approach is how easy it is to update Starling to the latest version.
Simply navigate into the repository's directory and `pull`:

  cd Starling-Framework
  git pull

That's much simpler than opening up the browser and manually downloading a new version, isn't it?

[NOTE]
====
Some additional information for advanced _Git_-users:

* All day-to-day development in Starling happens on the `master` branch.
* Stable releases are _tagged_ (like `v2.0`, `v2.0.1`, `v2.1`).
* Each tag is marked as a _Release_ on _GitHub_, at which time I'll also attach a precompiled SWC file.
====

=== Getting Help

The best of us get stuck sometimes.
You might hit a road block because of a bug in Starling, or maybe because of a problem that seems impossible to solve.
Either way, the Starling community won't leave you alone in your misery!
Here are some resources that you can go to when you need help.

Starling Forum::
That's the main hub of the Starling community.
With dozens of new posts each day, it's very likely that your problem has already been asked before, so be sure to make use of the _search_ feature.
If that doesn't help, feel free to register an account and ask away.
One of the most friendly and patient communities you'll find on the web! +
-> http://forum.starling-framework.org

Starling Manual::
ifdef::target-manual[The online manual you are reading right now.]
ifndef::target-manual[The online manual provides an extensive introduction to Starling.]
I try my best to keep it updated for each new release. +
-> http://manual.starling-framework.org

Starling Wiki::
The wiki contains links and articles about different Starling related topics, and most importantly: a list of Starling extensions.
We will discuss some of those later. +
-> http://wiki.starling-framework.org

API Reference::
Don't forget to consult the Starling API Reference for detailed information about all classes and methods. +
-> http://doc.starling-framework.org

Gamua Blog::
Keep up to date with the latest news about Starling via the Gamua blog.
I must admit I'm a little lazy when it comes to writing blog posts, but there will always be at least one for each Starling release. +
-> http://gamua.com/blog

Twitter::
I'm using several social networks, but the best way to reach me is via `@Gamua`.
Follow this account to get updates about new developments or links to other Starling-powered games. +
-> https://twitter.com/Gamua

