== What is Adobe AIR?
ifndef::imagesdir[:imagesdir: ../../img]

Just a few years ago, Adobe's _Flash Player_ was omnipresent when browsing the web.
At that time, it was basically the only choice when you wanted to create interactive or animated content for the web.
Browsers had very limited capabilities when it came to video, sound, and animation; and the few features they had were plagued by browser incompatibilities.
In short, it was a mess.

That's why _Adobe Flash_ was so popular.
It allowed designers and developers to create multimedia content in an intuitive authoring program (now called _Adobe Animate_), and ensured that it would look the same across all platforms.
With _ActionScript 3_, it also featured a language that was both easy to learn and very powerful.

NOTE: _Flash_ was originally created by _Macromedia_, which was acquired by Adobe in 2005.

Building on the popularity of its platform, Adobe realized that there was a demand to use the same technology for standalone applications that run outside the browser.
That's what the _Adobe AIR_ runtime is for.
Applications built with the _AIR SDK_ can be deployed as standalone applications that run on desktop (_Windows_, _macOS_) or mobile (_Android_, _iOS_).
Its standard library is a superset of the one from Flash, so you can do anything in _AIR_ that you can do in _Flash_; but it also provides a huge number of additional APIs for things like file system access or window management.

Of course, when you want to create a desktop application, you also need a way to create a graphical user interface, right?
Since standard Flash was not very well suited for this task, this was moved into another SDK: _Flex_ (now _Apache Flex_).
Flex also introduced an XML-based markup language (called _MXML_) to define user interface layouts.

TIP: For Starling, you don't need _Flex_, just the _AIR SDK_.

=== The current state of Flash and AIR

At the time of its introduction, _AIR_ was part of a trend summarized under the term "Rich Internet Applications" (_RIA_) -- a buzzword that was all the rage in the late 2000's.
There was a fierce competition between Adobe's _AIR_ and Microsoft's _Silverlight_ (as well as Sun's _JavaFX_).
Fast forward to the present day, though, and it's apparent that the tides have turned.
The winner is clearly _HTML5/JavaScript_, which is now the most popular technology stack when building applications with web technologies.
Even Adobe followed the trend and is adding more and more _HTML5_ support to its products.

TIP: When it comes to software development, don't fall into the trap of blindly following the masses.
For every problem, there are multiple solutions; some of them better suited than others.
Pick the tool you are most comfortable with; a tool that gets out of your way and lets you focus on the software you want to create.

Even though it might be no longer the "cool kid" in town, the __AIR/Flash-__platform is still an extremely attractive platform to build software with:

* Compared to the fragmented world of _HTML5_, where trending libraries change faster than Lady Gaga's costumes, it is very mature and easy to use.
* It comes with an extensive standard library that provides all the tools you need for day-to-day development.
* The Flash plug-in, while clearly on the decline for general websites, is still the standard for browser gaming.
  The majority of games on _Facebook_, for example, are still built with Flash.
* Especially combined with _Starling_ and _Feathers_, it provides one of the smoothest paths for true cross-platform development (targeting all major desktop and mobile platforms with a single code-base).

Talking about _Starling_ ... how does it fit into this picture?
